---
- name: Testing andrewrothstein.consul
  hosts: all
  tasks:
    - name: Installing andrewrothstein.consul
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'consul --version'
      ansible.builtin.command: /usr/local/bin/consul --version
      changed_when: false
      register: consul_test_output
    - name: Output from 'consul --version'
      ansible.builtin.debug:
        msg: '{{ consul_test_output.stdout }}'
