---
- name: installing consul binaries
  include_role:
    name: andrewrothstein.hashi
  vars:
    hashi_apps:
      - name: '{{ consul_app.name | default("consul") }}'
        ver: '{{ consul_app.ver | default(consul_ver) }}'
        meta: '{{ consul_app.meta | default("") }}'
