---
- name: download consul...
  become: '{{consul_privilege_escalate}}'
  become_user: root
  get_url:
    url: '{{consul_url}}'
    dest: /tmp/{{consul_zip}}
    checksum: '{{consul_checksum}}'
    mode: '0644'

- name: version specific directory for binary
  become: '{{consul_privilege_escalate}}'
  become_user: root
  file:
    path: '{{consul_install_dir}}/{{consul_name}}'
    state: directory
    mode: 0755

- name: unarchive consul...
  become: '{{consul_privilege_escalate}}'
  become_user: root
  unarchive:
    remote_src: yes
    src: /tmp/{{consul_zip}}
    dest: '{{consul_install_dir}}/{{consul_name}}'
    creates: '{{consul_install_dir}}/{{consul_name}}/consul'

- name: link consul...
  become: '{{consul_privilege_escalate}}'
  become_user: root
  file:
    src: '{{consul_install_dir}}/{{consul_name}}/consul'
    dest: '{{consul_install_dir}}/consul'
    state: link

- name: cleanup ...
  become: '{{consul_privilege_escalate}}'
  become_user: root
  when: consul_cleanup
  file:
    path: /tmp/{{consul_zip}}
    state: absent
