---
- name: create consul group
  group: name=consul state=present
  
- name: create consul user
  user: >-
    name=consul
    group=consul
    home={{consul_agent_data_dir}}
    state=present
    
- name: download consul...
  get_url: >
    url={{consul_url}}
    dest={{consul_agent_data_dir}}/{{consul_zip}}
    owner=consul
    group=consul
    mode=0644

- name: version specific directory for binary
  file: >-
    path=/usr/local/bin/{{consul_name}}
    state=directory
    owner=root
    group=root
    mode=0755
    
- name: unarchive consul...
  unarchive: >
    copy=no
    src={{consul_agent_data_dir}}/{{consul_zip}}
    dest=/usr/local/bin/{{consul_name}}
    creates=/usr/local/bin/{{consul_name}}/consul

- name: link consul...
  file: >-
    src=/usr/local/bin/{{consul_name}}/consul
    dest=/usr/local/bin/consul
    state=link
    force=yes

- name: create directories
  file: >-
    path={{item}}
    owner=consul
    group=consul
    state=directory
  with_items:
    - '{{consul_agent_etc_dir}}'
    - '{{consul_agent_data_dir}}'

- name: configure templates...
  template: >-
    src=etc/consul.d/{{consul_agent_template}}.j2
    dest={{consul_agent_etc_dir}}/consul.json
    owner=consul
    group=consul
    mode=0644

- name: install systemd service
  register: consul_service_modified
  template: >-
    src=usr/lib/systemd/system/consul.service.j2
    dest=/usr/lib/systemd/system/consul.service
    owner=root
    group=root
    mode=0644

- name: systemctl daemon-reload
  when: consul_service_modified|changed
  command: systemctl daemon-reload
    
- name: launch consul service
  service: name=consul enabled=true state=started
